Rspec編02 model spec
kuboyuya/sample_app_for_rspec pull request #2
Opened 2021-01-04 11:48 UTC by kuboyuya

概要
・.rspec ファイルに --format documentationを追記しました。
・taskモデルに関するバリデーションのテストを作成しました。
・FactoryBotを利用してテストデータを作成しました。

[![Image from Gyazo](https://i.gyazo.com/3e9fb369fdeed47cc7c73effd8a74fd9.png)](https://gyazo.com/3e9fb369fdeed47cc7c73effd8a74fd9)

2021-01-04 13:11 UTC, kuboyuya commented
上記の
「Fix: 解答を見てfactoryを修正」コミットは、task_spec.rbの修正も行っています。

2021-01-05 02:08 UTC, yuji91 requested changes
細かい点をいくつか指摘しました！

2021-01-05 02:08 UTC, yuji91 commented on spec/factories/users.rb
> +    password_confirmation {"password"}
細かいですが式展開しない文字列はシングルクォートで囲んだ方が良いですね。
また波括弧の間はスペースで区切ると見やすいです。

```suggestion
    password { 'password' }
    password_confirmation { 'password' }
```

2021-01-05 02:08 UTC, yuji91 commented on spec/models/task_spec.rb
> +        # エラーは空である
表現が分かりづらいと思ったので、修正した方が良いかと思いました。
```suggestion
        # バリデーション判定後のインスタンスの持つエラーメッセージの配列は空である
```

2021-01-05 11:29 UTC, merged